version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
  exclusions:
    presets:
      - std-error-handling

formatters:
  enable:
    - gofmt
    - goimports
